#!/bin/bash

cp python_latex/animate__data_8py.tex cpp_latex/
cp python_latex/animate__map_8py.tex cpp_latex/
cp python_latex/book__collaborate_8py.tex cpp_latex/
cp python_latex/book__measurements_8py.tex cpp_latex/
cp python_latex/download__data_8py.tex cpp_latex/
cp python_latex/helper__data_8py.tex cpp_latex/
cp python_latex/helper__plot_8py.tex cpp_latex/
cp python_latex/helper__system_8py.tex cpp_latex/
cp python_latex/plot__antenna_8py.tex cpp_latex/
cp python_latex/plot__bar__chart_8py.tex cpp_latex/
cp python_latex/plot__collaborate_8py.tex cpp_latex/
cp python_latex/plot__data_8py.tex cpp_latex/
cp python_latex/plot__data__distribution_8py.tex cpp_latex/
cp python_latex/plot__map_8py.tex cpp_latex/
cp python_latex/plot__measurement__analysis_8py.tex cpp_latex/
cp python_latex/plot__power_8py.tex cpp_latex/
cp python_latex/plot__regression_8py.tex cpp_latex/
cp python_latex/plot__series_8py.tex cpp_latex/
cp python_latex/plot__spectral__clustering_8py.tex cpp_latex/
cp python_latex/plot__tracks_8py.tex cpp_latex/
cp python_latex/process__netcdf_8py.tex cpp_latex/
cp python_latex/run__batch__command_8py.tex cpp_latex/
cp python_latex/scramble__tle__file_8py.tex cpp_latex/
cp python_latex/diff_analysis.pdf cpp_latex/
cp python_latex/power.pdf cpp_latex/
cp python_latex/map.pdf cpp_latex/
cp python_latex/measure.pdf cpp_latex/
cp python_latex/collaborate.pdf cpp_latex/
cp python_latex/constellations.pdf cpp_latex/
cp python_latex/data_analysis.pdf cpp_latex/
cp python_latex/regression.pdf cpp_latex/
cp python_latex/parameters.pdf cpp_latex/
cp python_latex/collab_cloud_meas_analysis.pdf cpp_latex/
cp python_latex/antennas.pdf cpp_latex/
cp python_latex/combined.pdf cpp_latex/
cp python_latex/clusters.pdf cpp_latex/
